# Generated by Django 4.2.3 on 2023-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_category_comment_project_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hasProject',
            field=models.BooleanField(default=False),
        ),
    ]
